### ISSUE TITLE
Access to the documentation

### ISSUE THREAD

**Issue by smigielski** [MphasisWyde/ewam-advanced-framework#1]
Hi, 

Can you share documentation somehow? It seems it is not available for me on https://mphasiswyde.atlassian.net/wiki/display/PTD/eWam+Advanced+Framework

**Comment by SebastienAndre** [comment]
Hi Marek,
We are going to give you access to this documentation.

Could you please confirm that you are working for Oberthur Technology Poland?

Regards,
Sébastien ANDRE

De : Marek Śmigielski [mailto:notifications@github.com]
Envoyé : mardi 14 juin 2016 11:39
À : MphasisWyde/ewam-advanced-framework <ewam-advanced-framework@noreply.github.com>
Objet : [MphasisWyde/ewam-advanced-framework] Access to the documentation (#1)


Hi,

Can you share documentation somehow? It seems it is not available for me on https://mphasiswyde.atlassian.net/wiki/display/PTD/eWam+Advanced+Framework

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/MphasisWyde/ewam-advanced-framework/issues/1>, or mute the thread<https://github.com/notifications/unsubscribe/AOptKy9eDp2GJ7Y9zKjLzE24AGTk5xALks5qLnapgaJpZM4I1Ios>.
Information transmitted by this e-mail is proprietary to Mphasis, its associated companies and/ or its customers and is intended 
for use only by the individual or entity to which it is addressed, and may contain information that is privileged, confidential or 
exempt from disclosure under applicable law. If you are not the intended recipient or it appears that this mail has been forwarded 
to you without proper authority, you are notified that any use or dissemination of this information in any manner is strictly 
prohibited. In such cases, please notify us immediately at mailmaster@mphasis.com and delete this mail from your records.

**Comment by smigielski** [comment]
Yes, you can contact me at m.smigielski[at]oberthur.com

**Comment by SebastienAndre** [comment]
Hi Marek,
The documentation is now available on this confluence instance : 
https://wydedocs.atlassian.net/wiki/display/PTD/eWam+Advanced+Framework
You will need to sign in.
Not that this documentation is frequently refreshed from https://mphasiswyde.atlassian.net/wiki/display/PTD/eWam+Advanced+Framework

Sebastien

**Comment by andie87** [comment]
Hi Sébastien ANDRE,

I also would like to access the documentation, 
my email : andi-mulya.indrianto@idemia.com
